### ISSUE TITLE
How to get all the products from whmcs

### ISSUE THREAD

**Issue by johnhenry15** [darthsoup/laravel-whmcs#1]
I am new to laravel 5.6 framework.
Now I am using laravel 5.6 and  php version is  7.2.2. I was add this package to my laravel application and configure to use my api url,username and password.But i didn't get any products from WHMCS. I get a blank page. 
here attached my code
 
`<?php 
namespace DarthSoup\Tests\Whmcs;
use Whmcs;
use DarthSoup\Whmcs\WhmcsServiceProvider;
use DarthSoup\Whmcs\tests\WhmcsServiceproviderTest;
class ServiceProvider extends TestCase
{
   public function GetProducts()
    {
             $data = [
            'action' => 'GetProducts',
            'gid' => 1,
            'response-type' =>'json',           
        ];     
        return view ($data);
   }
}`

**Comment by darthsoup** [comment]
I do not understand your example code, so here is one from a Controller

```
    /**
     * @return Response
     */
    public function index()
    {
        $product = \Whmcs::GetProducts([
            'pid' => '7'
        ]);
        
        return view('index', [
            'product' => $product
        ]);
    }
```

for your purpose

```
$product = \Whmcs::GetProducts([
   'gid' => '1'
]);
```
