### ISSUE TITLE
get whmcs client details in laravel+adminlte

### ISSUE THREAD

**Issue by mastura9696** [darthsoup/laravel-whmcs#10]
Hi.. 

I wanted to get all clients detail from whmcs to laravel+ adminlte.
I am new to programming so i need some guide where to put the code so that it appears at admin dashboard.
Here is the code that i found:        
` <?php
$whmcs = app('whmcs');
$whmcs->execute('GetClients', [
    'clientid' => '33'
]);?>`

Need you help urgently.
Thank you

**Comment by darthsoup** [comment]
Hi,

empty the array in the Execute method and you should get all clients.
