### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by LifeSteala** [darthsoup/laravel-whmcs#14]
I installed Laravel fresh today and ran this command to install your package.

`composer require darthsoup/laravel-whmcs`

Got this error:

`PS C:\laragon\www\timesheet> composer require darthsoup/laravel-whmcs`
`Using version ^0.2.6 for darthsoup/laravel-whmcs`
`./composer.json has been updated`
`Loading composer repositories with package information`
`Updating dependencies (including require-dev)`
`Your requirements could not be resolved to an installable set of packages.`

`  Problem 1`
`    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].`
`    - Can only install one of: guzzlehttp/guzzle[7.0.1, 6.5.x-dev].`
`    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.0.1].`
`    - darthsoup/laravel-whmcs 0.2.6 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].`
`    - Installation request for darthsoup/laravel-whmcs ^0.2.6 -> satisfiable by darthsoup/laravel-whmcs[0.2.6].`
`    - Installation request for guzzlehttp/guzzle (locked at 7.0.1, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].`

`Installation failed, reverting ./composer.json to its original content.`

What do I do to get past this please?

--
Laravel: 8.1.0
Windows 10
PHP 7.4

**Comment by darthsoup** [comment]
Hi,

you cannot currently use it with Guzzle 7.

**Comment by darthsoup** [comment]
Thanks to @stephandesouza with the new release its possible to use guzzle 7
