### ISSUE TITLE
An admin user is required  

### ISSUE THREAD

**Issue by privyreza** [darthsoup/laravel-whmcs#19]
My code was working all along, but when i upgraded to 8.1, I started getting the error:

```An admin user is required  ```

I have tried using the directs codes from https://developers.whmcs.com/api-reference/ and it works well with no issues.

**Comment by darthsoup** [comment]
are you using api credentials or admin/password to login?

**Comment by privyreza** [comment]
Thanks for responding. I am using api credentials

**Comment by darthsoup** [comment]
I don't understand at the moment why you are getting this. I also dont find any changes in the whmcs api documentation. WHMCS is always a big question mark :/

**Comment by privyreza** [comment]
Hi @darthsoup I noticed the issue could have started when I updated this module, and i think i know where the issue is, refer to attached screenshot.:

This line 
```$url = $this->getConfig()['apiurl'].'/api.php'; ```

Is adding an extra /api.php, so the resulting url is like: api.php/api.php

How can I fix this on the repo?

![Screenshot (1)](https://user-images.githubusercontent.com/20134879/108639459-474f5100-749d-11eb-9842-8d789ff65287.png)

**Comment by darthsoup** [comment]
i see, the config is slighty misleading

you can change the config by only using `https://url.to.whmcs.tld/whmcs/includes`

**Comment by jesussuarz** [comment]
> i see, the config is slighty misleading
> 
> you can change the config by only using `https://url.to.whmcs.tld/whmcs/includes`

Is there a way to achieve this request on localhost?

I do not want to do it through the internet, but to consult it directly from the directory ...

my apache has no output via 127.0.0.1 or localhost.

therefore I want to achieve this from a direct

for example...
/home/web/whmcs/includes

I am looking for this kind of connection: https://developers.whmcs.com/api/internal-api/


@darthsoup

**Comment by darthsoup** [comment]
@jesussuarz this is not working. this package is intened to use only with https connection. you can use it with localhost if you have your project on the same server

**Comment by bobimicroweber** [comment]
array:2 [▼
  "result" => "error"
  "message" => "An admin user is required"
]

i setup api credentinals..

**Comment by privyreza** [comment]
> i see, the config is slighty misleading
> 
> you can change the config by only using `https://url.to.whmcs.tld/whmcs/includes`

Can I create a pull request to include the changes i made?

**Comment by darthsoup** [comment]
@privyreza feel free to do so

**Comment by darthsoup** [comment]
should be fixed now with 0.3.1! thanks to @sherblot
