### ISSUE TITLE
Lumen 5.5 - Facade Issue

### ISSUE THREAD

**Issue by PV-Patrick** [darthsoup/laravel-whmcs#2]
I am trying to use this with Lumen 5.5 and not having much luck.  I cannot find any documentation for this project for how to configure for Laravel/Lumen.

I added the following to bootstrap/app.php

`$app->withFacades(true, ['DarthSoup\Whmcs\Facades\Whmcs' => 'Whmcs']);`
`$app->register(DarthSoup\Whmcs\WhmcsServiceProvider::class);`

What am I doing wrong?  Is the above necessary?  Any help is appreciated, thank you!

**Comment by PV-Patrick** [comment]
I actually got it working, for anyone else with this issue please see below.  Might you add it to the documentation as well.

In "bootstrap/app.php" Uncomment and add the following:
`$app->withFacades(true, ['DarthSoup\Whmcs\Facades\Whmcs' => 'Whmcs']);`
`$app->register(DarthSoup\Whmcs\WhmcsServiceProvider::class);`

To resolve the config_path() error / issue.  Create "app/Support/helpers.php" and add the following to that file:
`<?php
if ( ! function_exists('config_path'))
{
    /**
     * Get the configuration path.
     *
     * @param  string $path
     * @return string
     */
    function config_path($path = '')
    {
        return app()->basePath() . '/config' . ($path ? '/' . $path : $path);
    }
}`

Modify your composer.json so it looks like this:
`"autoload": {
    "psr-4": {
        "App\\": "app/"
    },
    "files": [
        "app/helpers.php"
    ]
},`

Lastly, run `composer dump-autoload` - This package should now work.

**Comment by darthsoup** [comment]
I have personally never used Lumen before, so its good to know that you actually got it working. 
So, i may look that i can change the registration behavior for Lumen in the next days.

**Comment by darthsoup** [comment]
I did a quick test with lumen and changed the boot function to check if its a laravel or lumen instance. Can you check if it now works with my latest change?

**Comment by PV-Patrick** [comment]
I just tested with a reinstall and it worked fine.

**Comment by PV-Patrick** [comment]
By default, Lumen doesn't have a config/ directory.  I didn't notice you changed the readme / directions so I tried it following your directions and it did not work.  I still had the config_path() error.

This also won't work with the Facade as they are not enabled by default like Laravel.

**Comment by darthsoup** [comment]
Well, then i am doing it wrong :D

If you want, you can make a PR. I'm not really experienced with Lumen
