### ISSUE TITLE
dependency injection of manager class not working

### ISSUE THREAD

**Issue by KatiaSishost** [darthsoup/laravel-whmcs#22]
Target [DarthSoup\Whmcs\Adapter\ConnectorInterface] is not instantiable while building [App\Http\Controllers\Backend\CustomerController, DarthSoup\Whmcs\WhmcsManager].

**Comment by prafullaranjan** [comment]
I am getting the same error, any resolution ? It's closed without comment.

**Comment by darthsoup** [comment]
A stacktrace would be helpful or an example of the controller

**Comment by ShrlGnwn** [comment]
I am getting the same error, any resolution ? It's closed without comment.

**Comment by darthsoup** [comment]
i need something to reproduce this error

**Comment by darthsoup** [comment]
i reproduced it myself. should be fixed now
