### ISSUE TITLE
How can I authenticate without config.php

### ISSUE THREAD

**Issue by dekts** [darthsoup/laravel-whmcs#26]
Hi Kevin,

I want to sync several companies with Standalone's Laravel platform where I have all the WHMCS credentials and domain links stored in database when a company is created. I have all the details stored in a database. After switching companies, I get credentials specific to the new company.

The credentials should be obtained from the database and authenticated with your package instead of manually setting them in the whmcs.php config file.

Would it be possible to create a way in this package where the user can get credentials from the database directly and authenticate when he or she calls the API?

**Comment by dekts** [comment]
Having gone through the other closed issue, I found a way to do it without the whmcs.php configuration file.

The following steps should be followed:

Step 1: To create an instance of Client class, place the client at the top of your class.

`use DarthSoup\WhmcsApi\Client;`

Step 2: The connection should be added to the constructor or method where you want to log in with your whmcs credentials.

```
$client = new Client();
$client->authenticate(
    company()->username,
    company()->password,
    Client::AUTH_LOGIN_CREDENTIALS
);
$client->url(company()->domain);
```

Step 3: To obtain the client, you need to use the Whmcs class you have registered in the app.php config and the syntax provided in the readme file.

`use Whmcs;` OR `use DarthSoup\Whmcs\Facades\Whmcs`

Get your data using the following syntax. I wrote this to fetch the client's data.

`$customers = Whmcs::client()->getClients();`

**Comment by darthsoup** [comment]
Hi, 

~~i assume you are using the old legacy version? right~~
~~try the newer version it has support for multiple connections~~

now i see, you created a custom whmcs client. so if you bypass the manager class you cant use the magic anymore :)

use `$client->client()->getClients()'

**fyi:** the architecture of this library has been changed with 1.0. the previous issues are no longer valid.

**Comment by dekts** [comment]
Yes, I used the [php-whmcs-api](https://github.com/darthsoup/php-whmcs-api) library to create a client.

Then I am able to access the API using the `use DarthSoup\Whmcs\Facades\Whmcs`

Here's what I did:
`$clients = Whmcs::client()->getClients();`

**Comment by darthsoup** [comment]
Yea, but if you use the standalone php-whmcs-api you can't use the laravel library anymore.
