### ISSUE TITLE
Configurable timeout

### ISSUE THREAD

**Issue by bytestream** [darthsoup/laravel-whmcs#27]
Guzzle defaults to an indefinite timeout. It would be ideal if the connection to WHMCS had a configurable timeout so prevent scripts running forever.

**Comment by darthsoup** [comment]
Interesting! 
I need to see where I can implement this most effectively because this only wraps the php-whmcs-api where you can add own PSR compatible http-client

**Comment by bytestream** [comment]
@darthsoup if you point me in the right direction I'd be happy to send a PR otherwise I'll leave it to you

**Comment by darthsoup** [comment]
@bytestream i started something with commit https://github.com/darthsoup/laravel-whmcs/commit/ea7138e56a389146956aa84f125451f93f41e0e2
