### ISSUE TITLE
Authentication example

### ISSUE THREAD

**Issue by lokmanm** [darthsoup/laravel-whmcs#29]
Hi sorry for opening an issue but your Discussion tab is not activated.

We have a client who has a wmcs installation and we wanted to use this package to make a better interface for the users.
Do you have any examples on how to authenticate users with Laravel ? With users I mean the clients, not the admin.

Thanks.

**Comment by darthsoup** [comment]
it depends if you can create a website with the available functions of the Api, otherwise it might be possible to create a UserProvider for Laravels auth system but this is out of scope of this library.

**Comment by lokmanm** [comment]
> it depends if you can create a website with the available functions of the Api, otherwise it might be possible to create a UserProvider for Laravels auth system but this is out of scope of this library.

Yes we can create it with the available functions.

I was just interested on how people handle authentication with clients and whmcs. Is there a recommended way of doing it or ?

**Comment by darthsoup** [comment]
Sorry, i dont know that. this is out of my scope for the library.

**Comment by lokmanm** [comment]
@darthsoup I found what I was looking for. I will leave it here incase anyone else stumbles upon this issue.

[Laravel WHMCS Up](https://github.com/sburina/laravel-whmcs-up)
