### ISSUE TITLE
Add "Authenticating With API Credentials"

### ISSUE THREAD

**Issue by darthsoup** [darthsoup/laravel-whmcs#3]
Currently only "Authenticating With Login Credentials" is possible

**Comment by PV-Patrick** [comment]
Was just about to ask you to add this. haha!

**Comment by william1888** [comment]
Is there any update on this? I have a current project where I use the new API auth and I would like to replace my implementation with yours.

**Comment by darthsoup** [comment]
hi, I am still using WHMCS 7.1. I will see that I can implement this at short term.

**Comment by darthsoup** [comment]
@exwizzard @PV-Patrick its implemented now
