### ISSUE TITLE
cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://billing.pakchamp.com/includes/api.php

### ISSUE THREAD

**Issue by engradnanalipakchamp** [darthsoup/laravel-whmcs#31]
cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://billing.pakchamp.com/includes/api.php
I am using darthsoup/laravel-whmcs package I set WHMCS_API_URL="https://billing.pakchamp.com/", WHMCS_API_IDENTIFIER, WHMCS_API_SECRET and WHMCS_API_ACCESSKEY but I am getting this above mentioned error can you please suggest where I am wrong.

**Comment by darthsoup** [comment]
Not a packge problem, look at your ssl certificate.
