### ISSUE TITLE
No support for Laravel 10

### ISSUE THREAD

**Issue by JobsFav** [darthsoup/laravel-whmcs#33]
Problem 1
    - darthsoup/laravel-whmcs 1.2.0 requires graham-campbell/manager ^4.7 -> satisfiable by graham-campbell/manager[v4.7.0].
    - darthsoup/laravel-whmcs[0.1, ..., 0.1.1] require illuminate/support 5.2.*|5.3.*|5.4.*|5.5.* -> found illuminate/support[v5.2.0, ..., v5.5.44] but these were not loaded, likely because it conflicts with another require.
    - darthsoup/laravel-whmcs[0.1.2, ..., 0.2.0] require illuminate/support 5.2.*|5.3.*|5.4.*|5.5.*|5.6.* -> found illuminate/support[v5.2.0, ..., v5.6.39] but these were not loaded, likely because it conflicts with another require.
    - darthsoup/laravel-whmcs[0.2.1, ..., 0.2.2] require illuminate/support 5.2.*|5.3.*|5.4.*|5.5.*|5.6.*|5.7.* -> found illuminate/support[v5.2.0, ..., v5.7.28] but these were not loaded, likely because it conflicts with another require.
    - darthsoup/laravel-whmcs 0.2.3 requires illuminate/support 5.2.*|5.3.*|5.4.*|5.5.*|5.6.*|5.7.*|5.8.* -> found illuminate/support[v5.2.0, ..., v5.8.36] but these were not loaded, likely because it conflicts with another require.
    - darthsoup/laravel-whmcs 0.2.4 requires illuminate/support ^5.2|^6.0 -> found illuminate/support[v5.2.0, ..., v5.8.36, v6.0.0, ..., v6.20.44] but these were not loaded, likely because it conflicts with another require.
    - darthsoup/laravel-whmcs 0.2.5 requires illuminate/support ^5.2|^6.0|^7.0 -> found illuminate/support[v5.2.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6] but these were not loaded, likely because it conflicts with another require.
    - darthsoup/laravel-whmcs[0.2.6, ..., 0.3.2] require illuminate/support ^5.2|^6|^7|^8 -> found illuminate/support[v5.2.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - darthsoup/laravel-whmcs[1.0.0, ..., 1.1.0] require illuminate/support ^7.0|^8.0|^9.0 -> found illuminate/support[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.
    - graham-campbell/manager v4.7.0 requires illuminate/contracts ^5.5 || ^6.0 || ^7.0 || ^8.0 || ^9.0 -> found illuminate/contracts[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires darthsoup/laravel-whmcs * -> satisfiable by darthsoup/laravel-whmcs[0.1, ..., 0.3.2, 1.0.0, 1.1.0, 1.2.0].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

Please update the dependency for graham-campbell/manager to the latest version 5.0.

**Comment by darthsoup** [comment]
i need some testing with laravel 10 before i publish the version, maybe over the weekend

**Comment by JobsFav** [comment]
Ok, thank you!

**Comment by darthsoup** [comment]
should work now, give it a try ;)
