### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by esglobal** [darthsoup/laravel-whmcs#35]
Hi team, any plans to support PHP 8.1?

**Comment by darthsoup** [comment]
Do you have a specific error? The library actually has support for PHP 8.1.

**Comment by darthsoup** [comment]
did some changes to the main library yesterday because it didnt work on php 8.2. it might work now also for 8.1

**Comment by esglobal** [comment]
Tested with 8.2 as well and it works like a charm, thank you.
