### ISSUE TITLE
How to add clients in whmcs using controller in laravel 5.6

### ISSUE THREAD

**Issue by johnhenry15** [darthsoup/laravel-whmcs#4]
My laravel controller code is given below:

        `public function insertform(){
         return view('clientlayout.main.signup');
          } 

      public function insert(Request  $request){
        
         $firstname =  $_POST('firstname');
         $lastname =  $_POST('lastname');
         $companyname =  $_POST('companyname');
         $email =  $_POST('email');
        $address1 =  $_POST('address1');
         $address2 =  $_POST('address2');
        $city =  $_POST('city');
         $state =  $_POST('state');
       $postcode =  $_POST('postcode');
        $country =  $_POST('country');
        $phonenumber =  $_POST('phonenumber');
        $password =  $_POST('password');
        $request=array('firstname'=>$firstname,"lastname"=>$lastname,"city"=>$city,"email"=>$email,"country"=>$country,
       "address1"=>$address1,"address2"=>$address2,"state"=>$state,"postcode"=>$postcode,"password"=>$password,
    "phonenumber"=>$phonenumber,"companyname"=>$companyname);
     Whmcs::AddClient($request);
   
    Whmcs::create($request->all());
    return redirect()->back();
        }
`

The code in the view file is given as follows:

        ` <form class="container" action="{{ route('product.insert') }}" id="needs-validation" 
            method="post" novalidate>

           <input type = "hidden" name = "_token" value = "<?php echo csrf_token(); 
            ?>">
           <div class="row">
           <div class="col-lg-6 col-sm-6 col-12">
           <div class="form-group">
            <label class="text-inverse custom" 
            for="validationCustom01">First Name
            <span class="req">*</span>
            </label>
            <input type="text" name="firstname" class="form-control" 
             id="validationCustom01"  placeholder="First name"
              value="" required maxlength="25" onKeyPress="return ValidateAlpha(event);" 
               style="background-color: rgba(19, 35, 47, 0.4); color:#fff;">
              <div class="invalid-feedback">
               Enter Your Firstname
               </div>
               </div>
               </div>

               </div> 
               </form>`

My Route file code is as follows:

       `Route::get('insert', 'ProductController@insertform');
        Route::post('create', 'ProductController@insert')->name('product.insert');`

Suggest me a solution to post the client details into WHMCS.

**Comment by darthsoup** [comment]
Can you provide a Error message for me?

---

One more example controller method for you

```
public function insert(Request $request)
{
    Whmcs::AddClient([
        'firstname' => $this->request->get('firstname'),
        // your other parameters
    ]);
    
    return redirect()->back();
}
```

The method `Whmcs::create` does not exist
