### ISSUE TITLE
Illegal string offset 'action' issue

### ISSUE THREAD

**Issue by mining016** [darthsoup/laravel-whmcs#6]
While using this with any Cart Package ( "darryldecode/cart": "~4.0",) on adding cart it is showing Illegal string offset 'action' issue.

http://prntscr.com/kv30hy

**Comment by darthsoup** [comment]
Can you provide some code samples?

**Comment by CodeWithJuber** [comment]
getting same issue

**Comment by darthsoup** [comment]
Can you provide some code samples?
