### ISSUE TITLE
Cart alias conflict

### ISSUE THREAD

**Issue by ghost** [darthsoup/laravel-whmcs#7]
Hi I am using the hardevine/LaravelShoppingcart packacge and I think it is conflicting with your package.

I noticed in your composer.json the following line:

` "Cart": "DarthSoup\\Whmcs\\Facades\\Whmcs" `

Should this not say ```Whmcs```?

**Comment by ovvessem** [comment]
Created a PR to change the alias in the composer.json #8

**Comment by darthsoup** [comment]
oh wupsi, never noticed.
sorry for the long delay, new release is out
