### ISSUE TITLE
Handle Multiple WHMCS APIs

### ISSUE THREAD

**Issue by DimitarDechew** [darthsoup/laravel-whmcs#9]
Hello,
I want to control more than 1 WHMCS Installation using your great package. When I firstly installed the package I saw that you support Dependency Injection, but now it's gone from the documentation. Can you give me an advice how to manage more than 1 WHMCS Installation using API Authentication.

**Comment by darthsoup** [comment]
Hi,

that is actually not possible. You have to initialize the WhmcsManager class by yourself with your own credentials.
